import { Inter } from 'next/font/google';
import '@/styles/globals.scss';
import Header from '@/components/header/Header';
import { GlobalProvider } from '@/hooks/useGlobalData';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<GlobalProvider>
					<main className='container'>
						<Header />
						{children}
					</main>
				</GlobalProvider>
			</body>
		</html>
	);
}
